name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup and Build
        uses: ./.github/workflows/setup-node.yml
        with:
          script: npm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: |
            dist
            logs
